//roadMap of fullStack developer
/*
Foundation
Foundation Javascript, async nature of JS
Node.js and its runtime=
Databases (NoSQL/SQL)
Mongo and Postgres deep dive
Typescript beginner to advance
Backend
Backend communication protocols
Express basic to advance
ORMs
Middlewares, routes, status codes, global catches
Zod
MonoRepos, turborepo
Serverless Backends
OpenAPI Spec
Autogenerated clients
Authentication using external libraries
Scaling Node.js, performance benchmarks
Deploying npm packages
 

Frontend

Reconcilers and Frontend frameworks
React beginner to advance
Internals of state, Context API
State management using recoil
CSS you need to know of, Flexbox, basic styling
Frontend UI frameworks, Deep dive into Tailwind
Containerization, Docker
Next.js
Custom hooks
In house auth using next auth
 






*/ 




//what is javascipt
//javascipt is high level interpreted programming language
//Prilimary use for fronted development 

//what is high level
//high level means easy to understands and deals with loop and function

//what is interpreted
//interpreted means not comiple before it can run
