//roadMap of fullStack developer
/*
Foundation
Foundation Javascript, async nature of JS
Node.js and its runtime=
Databases (NoSQL/SQL)
Mongo and Postgres deep dive
Typescript beginner to advance
Backend
Backend communication protocols
Express basic to advance
ORMs
Middlewares, routes, status codes, global catches
Zod
MonoRepos, turborepo
Serverless Backends
OpenAPI Spec
Autogenerated clients
Authentication using external libraries
Scaling Node.js, performance benchmarks
Deploying npm packages


Frontend

Reconcilers and Frontend frameworks
React beginner to advance
Internals of state, Context API
State management using recoil
CSS you need to know of, Flexbox, basic styling
Frontend UI frameworks, Deep dive into Tailwind
Containerization, Docker
Next.js
Custom hooks
In house auth using next auth







*/




//what is javascipt
//javascipt is high level interpreted programming language
//Prilimary use for fronted development

//what is high level
//high level means easy to understands and deals with loop and function

//what is interpreted
//interpreted means not comiple before it can run


//what are the data types in javascript?

//primitive datatype
//1)string 2)symbol 3)null 4)number 5)undefined 6)boolean

//non-primitive
//object


//what is diffence between let var and const?
//1)let and const are block scoped while var is function scope
//2)hoisting not possible in let and const but in var hoisting is possible
//3)ES6 introduced let and const and var is before ES6 introduced
//4)let and const redecalration not allowed but var redecalation is allowed

//what is Hoisting in javascipt?
//Hoisting is javascipt behavior where the variable and function declartion are moved to the top of their      containing scope during the compilation phase.

//what is closure in javascipt?
//closure are the function that have to access the variable from function from the another function scope is called as closure

// function outerFunction() {
//     let variable1 = "outer function ";
//     function inner() {
//         console.log(variable1);

//     }
//     return inner;
// }

// let closure = outerFunction();
// closure();


//what is callback
//callback are the function passed as an argument to the another function is called as callback function

// function hello() {
//     console.log("hello world");
// }
// setTimeout(hello, 2000);


// function sum(a, b) {
//     console.log(a + b);
// }

// function calculator(a, b, sum) {
//     sum(a, b);
// }

// calculator(1, 2, sum);


//what is callback Hell
//nested callback is called callback hell



//what is this keyword in javascipt?




